### ISSUE TITLE
Black Screen - Win10-gpu

### ISSUE THREAD

**Issue by MrDuartePT** [mysteryx93/GPU-Passthrough-with-Optimus-Manager-Guide#3]
When i use your script my VM stay with black screen after starting to boot windows. And the VM sems to crash, when i use the static vm with the nvidia driver blacklisted with works as intended.

![image](https://user-images.githubusercontent.com/68701049/199528749-29e35d09-5c22-4bba-a58a-ddbf6367d1ca.png)

lspcie output

![image](https://user-images.githubusercontent.com/68701049/199528984-6eefd92e-125b-4d66-a852-383ac34f32f4.png)

bind gpui script

```
#!/bin/bash
set -x

# Shut down display to release GPU
# Put Y in the stdin to avoid prompting for confirmation if using wayland
optimus-manager --no-confirm --switch integrated <<< "Y"
systemctl stop display-manager.service

# Unload NVidia
modprobe -r nvidia_uvm
modprobe -r nvidia_drm
modprobe -r nvidia_modeset
modprobe -r nvidia

# Unbind the GPU from display driver
virsh nodedev-detach pci_0000_01_00_0
virsh nodedev-detach pci_0000_01_00_1

# Load VFIO
modprobe vfio_pci
modprobe vfio_iommu_type1
modprobe vfio

# Restart display
systemctl restart display-manager.service
#!/bin/bash
set -x

# Shut down display to release GPU
# Put Y in the stdin to avoid prompting for confirmation if using wayland
optimus-manager --no-confirm --switch integrated <<< "Y"
systemctl stop display-manager.service

# Unload NVidia
modprobe -r nvidia_uvm
modprobe -r nvidia_drm
modprobe -r nvidia_modeset
modprobe -r nvidia

# Unbind the GPU from display driver
virsh nodedev-detach pci_0000_01_00_0
virsh nodedev-detach pci_0000_01_00_1

# Load VFIO
modprobe vfio_pci
modprobe vfio_iommu_type1
modprobe vfio

# Restart display
systemctl restart display-manager.service


```
unbind gpu script
```
#!/bin/bash
set -x

# Shut down display to release GPU
# Put Y in the stdin to avoid prompting for confirmation if using wayland
optimus-manager --no-confirm --switch integrated <<< "Y"
systemctl stop display-manager.service

# Unload NVidia
modprobe -r nvidia_uvm
modprobe -r nvidia_drm
modprobe -r nvidia_modeset
modprobe -r nvidia

# Unbind the GPU from display driver
virsh nodedev-detach pci_0000_01_00_0
virsh nodedev-detach pci_0000_01_00_1

# Load VFIO
modprobe vfio_pci
modprobe vfio_iommu_type1
modprobe vfio

# Restart display
systemctl restart display-manager.service
```

**Comment by mysteryx93** [comment]
I do not know, perhaps you could ask at some of the resources linked in the article. Once you find the solution, let me know what it was, perhaps I could add a note to cover your issue.

**Comment by MrDuartePT** [comment]
I resolve by adding this lines to xml file
```
<features>
    ...
    <hyperv>
        <relaxed state="on"/>
        <vapic state="on"/>
        <spinlocks state="on" retries="8191"/>
        <vendor_id state="on" value="kvm hyperv"/>
    </hyperv>
    ...
</features>
```

```
<features>
    ...
    <hyperv>
        ...
    </hyperv>
    <kvm>
      <hidden state="on"/>
    </kvm>
    ...
</features>
```

```
<features>
    ...
    <ioapic driver="kvm"/>
</features>
```
My PC is a Legion 5 with AMD Ryzen 7 5800H and RTX 3070, it have a mux swicth. I dont know this is specif to my laptop or to the RTX lineup.

I found this solution on this github repo: https://github.com/bryansteiner/gpu-passthrough-tutorial#part3

Here are my full xml: https://pastebin.com/WvE34trU

**Comment by mysteryx93** [comment]
Hum. Those options are to solve the Error 43 problem where NVidia blocks virtualization. They removed that block recently. So why do you still  need this?

**Comment by MrDuartePT** [comment]
After some further testing I notice the driver have a warning in device manager with error 43.
![image](https://user-images.githubusercontent.com/68701049/199844278-bf849b4d-1b86-4d27-b77c-6cd4473d251d.png)

Edit: After more testing, I turn on the laptop with graphic static bind and work. Then run the unbind script to unbind the card, and all work as intended (It not problem to run hybrid mode in battery power because I have Runtime D3 power management and my graphic stay power off when not in use), when I try to bind the gpu again the vm crash when loading windows and stay in the back screen, is nothing about the error 43, or this was a result of driver/kernel update or my system doesn’t like dynamic binding.

**Comment by MrDuartePT** [comment]
Ok I found the problem is bug introduce after kernel 5.19. I find the answer in this repo https://github.com/raifcoonjah/KVM-LenovoLegion5/tree/master/Arch, this is specific to my laptop. I gonna close the issue, thanks for your help. I think you can add this information in repo if is relevant. 
I think I gonna downgrade to LTS kernel and wait for a resolution 

Reddit post: https://www.reddit.com/r/VFIO/comments/xti1t1/vm_shutdown_results_to_blackscreen_past_51819/

Bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=215472

Edit:works in the LTS kernel but because i lose wifi because of the drivers, i prefer to use the static method the downside is necessary to reboot when i want to use the gpu, i will send a comment when the issue is resolve in the new kernel.

**Comment by mysteryx93** [comment]
I've also had serious issues with some recent kernels; switched to a different kernel `linux-xanmod-edge` and it works. Not sure if it's related to your issue. Many people reported GPU-related issues related to the kernels lately.

**Comment by MrDuartePT** [comment]
Yup switching to xanmod-edge kernel work now!

**Comment by mysteryx93** [comment]
That kernel is also considerably faster.
